import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const rubixMC = localFont({
  src: [
    {
      path: './fonts/RubixMC-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-ExtraLightItalic.ttf',
      weight: '200',
      style: 'italic',
    },
    {
      path: './fonts/RubixMC-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-LightItalic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: './fonts/RubixMC-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/RubixMC-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-MediumItalic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: './fonts/RubixMC-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-SemiBoldItalic.ttf',
      weight: '600',
      style: 'italic',
    },
    {
      path: './fonts/RubixMC-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
    {
      path: './fonts/RubixMC-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-ExtraBoldItalic.ttf',
      weight: '800',
      style: 'italic',
    },
    {
      path: './fonts/RubixMC-Black.ttf',
      weight: '900',
      style: 'normal',
    },
    {
      path: './fonts/RubixMC-BlackItalic.ttf',
      weight: '900',
      style: 'italic',
    },
  ],
  variable: "--font-rubix-mc",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubixMC.variable} ${rubixMC.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
