# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  # Run on pushes to main/master branch
  push:
    branches: [ main, master ]
  # Run on pull requests
  pull_request:
    branches: [ main, master ]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Don't fail the workflow on visual changes
          exitZeroOnChanges: true 